// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzfqhflssywbciwqfjan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZnFoZmxzc3l3YmNpd3FmamFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MzQzODQsImV4cCI6MjA3NjAxMDM4NH0.FqKuytv_--dupkvByIdP3yKKUxQ5j6YRBP4lyk4GZhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});